title: scribbles
description: jekyll blog test
theme: minima
baseurl: ""
url: "https://yourusername.github.io"

# Navigation links
nav:
  - name: "about"
    link: /about/
  - name: "blog"
    link: /blog/
  - name: "writeups"
    link: /writeups/

collections:
  writeups:
    output: true
    permalink: /writeups/:path/
